out_http: adding support for intermediate certificates
fluent/fluentd pull request #3101
Opened 2020-08-10 06:08 UTC by tyarimi

Signed-off-by: Tzach Yarimi <tyarimi@salesforce.com>

**Which issue(s) this PR fixes**: 
Fixes #

**What this PR does / why we need it**: 
Add support for sending a client certificate chain for mutual TLS authentication in the `out_http` plugin.

**Docs Changes**:

**Release Note**:

2020-08-19 17:41 UTC, repeatedly commented
@nurse This patch modifies Net::HTTP directly. Do you know this approach is safe or not?

2020-10-07 07:42 UTC, tyarimi commented
Hi folks. Any chance of merging this PR? We have been running it in production for some time now and it works fine.

2020-10-07 08:20 UTC, nurse commented
Of course it's not safe. It should use public APIs.

2020-10-07 08:31 UTC, tyarimi commented
@nurse `extra_chain_cert` was added in a later version of ruby. Is there any alternative?

2020-10-07 08:38 UTC, nurse commented
Well, it should add more comment for example referring https://github.com/ruby/ruby/commit/31af0dafba6d3769d2a39617c0dddedb97883712#diff-8c2ab8e0fb4f052e1d95ab6334e192c1
Also it should have a condition to avoid the monkey patch runs even if latest ruby.

2020-10-07 09:17 UTC, tyarimi commented
@nurse I added the comment, but I'm not sure how to implement the conditional patching (not a ruby expert). Can you please help with that?

2020-10-07 09:59 UTC, nobu commented on lib/fluent/plugin/out_http.rb
> +          bundle_certs = bundle.scan(/-----BEGIN CERTIFICATE-----(?:.|\n)+?-----END CERTIFICATE-----/)
This regexp seems to match also the middle of a line, is this intentional?

2020-10-07 21:32 UTC, nurse requested changes

2020-10-07 21:32 UTC, nurse commented on lib/fluent/plugin/out_http.rb
> +end
With assuming SSL_ATTRIBUTES include :extra_chain_cert if SSL_IVNAMES include :@ extra_chain_cert, single condition can enclose the definitions.
```suggestion
unless SSL_IVNAMES.include?(:@extra_chain_cert)
  class Net::HTTP
    SSL_IVNAMES << :@extra_chain_cert 
    SSL_ATTRIBUTES << :extra_chain_cert
    attr_accessor :extra_chain_cert
  end
end
```

2020-10-08 07:06 UTC, tyarimi commented
Closing this PR in favor of #3146 (switching head branch)

2020-10-08 07:06 UTC, closed without merging