Fix line skipping issue in receive_lines method
fluent/fluentd pull request #4530
Opened 2024-06-17 00:18 UTC by yugeeklab

Which issue(s) this PR fixes:
Fixes https://github.com/fluent/fluentd/issues/4494
recoverd from #4491 

What this PR does / why we need it:
Before this patch, long lines could cause breakdowns in fluentd, potentially posing a vulnerability. With this patch, max_line_size will be integrated into the FIFO, enabling the system to skip lines exceeding the maximum size before executing receive_lines.

Docs Changes:

Release Note:

2024-06-17 00:57 UTC, daipom commented
@yugeeklab I have pushed the commits for https://github.com/fluent/fluentd/pull/4491#issuecomment-2162508391.

2024-06-17 01:59 UTC, daipom approved these changes
Thanks! LGTM.
I will wait a bit to merge for other maintainers.

2024-07-06 01:15 UTC, ashie requested changes
Basically it look good to me, thanks for your contribution!
I've added some nitpick comments about logging.

In addition, it would be happy if we can simplify `FIFO#read_lines` to make easy to read although I have no idea about it yet.
What do you think about these my comments? @daipom

2024-07-08 03:16 UTC, daipom commented on lib/fluent/plugin/in_tail.rb
> +              @log.debug("skipped line: ") { convert(rbuf).chomp }
Thanks!
Fixed: 955cee5681f2c1cb375364a421ac1bdc2364e811

2024-07-08 03:16 UTC, daipom commented on lib/fluent/plugin/in_tail.rb
> +            @skip_current_line = true
Thanks!
Fixed: 955cee5681f2c1cb375364a421ac1bdc2364e811

2024-07-08 03:19 UTC, ashie approved these changes
LGTM
Thanks!

2024-07-08 03:22 UTC, daipom commented
> In addition, it would be happy if we can simplify `FIFO#read_lines` to make easy to read although I have no idea about it yet. What do you think about these my comments? @daipom

Thanks for your comments!
About debug messages, I have added a fix: 955cee5681f2c1cb375364a421ac1bdc2364e811.

About the simplification, I have the same opinion. I'll think about it for a bit.
If I come up with a good idea, I will add a fix.
Thanks!

2024-07-14 05:56 UTC, merged