in_exec: add option 'encoding' to handle non-ASCII characters
fluent/fluentd pull request #4533
Opened 2024-06-19 11:13 UTC by daipom

**Which issue(s) this PR fixes**: 
* Fixes #4460

**What this PR does / why we need it**: 
Add option: `encoding` to handle non-ASCII characters.

**Docs Changes**:
TODO

**Release Note**: 
Same as the title.

2024-06-20 11:06 UTC, kenhys requested changes

2024-06-20 11:06 UTC, kenhys commented on lib/fluent/plugin/in_exec.rb
> +    desc 'The encoding to receive the result of the command, especially for none-ascii characters.'
```suggestion
    desc 'The encoding to receive the result of the command, especially for non-ascii characters.'
```

2024-06-20 11:06 UTC, kenhys commented on test/plugin/test_in_exec.rb
> +    test 'can handle none-ascii characters' do |additional_setting|
```suggestion
    test 'can handle non-ascii characters' do |additional_setting|
```

2024-06-20 11:08 UTC, daipom commented
Thanks! Applied.

2024-07-07 08:29 UTC, ashie approved these changes
LGTM
Thanks!

2024-07-07 08:29 UTC, merged