tests: use never instead of dont_allow
fluent/fluentd pull request #4671
Opened 2024-10-16 09:48 UTC by Watson1978

**Which issue(s) this PR fixes**: 
Fixes #4063

**What this PR does / why we need it**: 

**Docs Changes**:

**Release Note**:

2024-10-17 11:00 UTC, daipom requested changes
Thanks for this fix!
Please fix the following points.

2024-10-17 23:38 UTC, Watson1978 commented on test/plugin/out_forward/test_socket_cache.rb
> +      sock2 = mock!.close.never
Fixed

2024-10-18 01:34 UTC, daipom commented
I'm checking if this failure on Windows has something to do with this change.

```
1) Failure: test: multiple values are set to RUBYOPT(TestFluentdCommand::configured to run 2 workers):
  log doesn't match.
  <"[7684, #<Thread:0x0000015755e11768 run>, #<NoMethodError: undefined method `ignored?' for #<Gem::Specification:0x000001575b219c98 @extension_dir=nil, @full_gem_path=nil, @gem_dir=nil, @ignored=nil, @bin_dir=nil, @cache_dir=nil, @cache_file=nil, @doc_dir=nil, @ri_dir=nil, @spec_dir=nil, @spec_file=nil, @gems_dir=\"C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/gems/3.1.0/gems\", @base_dir=\"C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/gems/3.1.0\", @loaded=false, @activated=false, @loaded_from=\"C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/gems/3.1.0/specifications/power_assert-2.0.4.gemspec\", @original_platform=nil, @installed_by_version=#<Gem::Version \"3.3.27\">, @autorequire=nil, @date=2024-10-03 00:00:00 UTC, @description=\"Power Assert shows each value of variables and method calls in the expression. It is useful for testing, providing which value wasn't correct when the condition is not satisfied.\", @email=[\"kazuki@callcc.net\"], @homepage=\"[https://github.com/ruby/power_assert\](https://github.com/ruby/power_assert/)", @name=\"power_assert\", @post_install_message=nil, @signing_key=nil, @summary=\"Power Assert for Ruby\", @version=#<Gem::Version \"2.0.4\">, @authors=[\"Kazuki Tsujimoto\"], @bindir=\"exe\", @cert_chain=[], @dependencies=[], @executables=[], @extensions=[], @extra_rdoc_files=[\"README.md\"], @files=[\"README.md\"], @licenses=[\"BSD-2-Clause\", \"Ruby\"], @metadata={}, @platform=\"ruby\", @rdoc_options=[\"--main\", \"README.md\"], @require_paths=[\"lib\"], @required_ruby_version=#<Gem::Requirement:0x000001575b219ab8 @requirements=[[\">=\", #<Gem::Version \"0\">]]>, @required_rubygems_version=#<Gem::Requirement:0x000001575b219900 @requirements=[[\">=\", #<Gem::Version \"0\">]]>, @requirements=[], @rubygems_version=\"3.3.27\", @specification_version=4, @test_files=[], @new_platform=\"ruby\", @full_name=\"power_assert-2.0.4\" power_assert-2.0.4>\r\n" +
  "Did you mean?  ignored=>, [\"C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/3.1.0/rubygems/specification.rb:2163:in `method_missing'\", \"C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:273:in `reject'\", \"C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:273:in `matching_specs'\", \"C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/3.1.0/rubygems/dependency.rb:303:in `to_specs'\", \"C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/3.1.0/rubygems/specification.rb:1080:in `block in unresolved_specs'\", \"C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/3.1.0/rubygems/specification.rb:1080:in `map'\", \"C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/3.1.0/rubygems/specification.rb:1080:in `unresolved_specs'\", \"C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/3.1.0/rubygems/specification.rb:1058:in `find_in_unresolved'\", \"<internal:C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:101:in `require'\", \"C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:298:in `<module:Gem>'\", \"C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:25:in `<top (required)>'\", \"C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.22/lib/bundler.rb:10:in `require_relative'\", \"C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.22/lib/bundler.rb:10:in `<top (required)>'\", \"C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.22/lib/bundler/setup.rb:6:in `require_relative'\", \"C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.22/lib/bundler/setup.rb:6:in `<top (required)>'\", \"<internal:C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:148:in `require'\", \"<internal:C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:148:in `require'\"]]\r\n" +
  "[7684, #<Thread:0x0000015755e11768 run>, #<RuntimeError: CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true>, [\"<internal:C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `ensure in require'\", \"<internal:C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `require'\", \"C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:298:in `<module:Gem>'\", \"C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:25:in `<top (required)>'\", \"C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.22/lib/bundler.rb:10:in `require_relative'\", \"C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.22/lib/bundler.rb:10:in `<top (required)>'\", \"C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.22/lib/bundler/setup.rb:6:in `require_relative'\", \"C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.22/lib/bundler/setup.rb:6:in `<top (required)>'\", \"<internal:C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:148:in `require'\", \"<internal:C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:148:in `require'\"]]\r\n" +
  "<internal:C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)\r\n" +
  "\tfrom <internal:C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `require'\r\n" +
  "<internal:C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)\r\n" +
  "\tfrom <internal:C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `require'\r\n" +
  "\tfrom C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:298:in `<module:Gem>'\r\n" +
  "\tfrom C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:25:in `<top (required)>'\r\n" +
  "\tfrom C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.22/lib/bundler.rb:10:in `require_relative'\r\n" +
  "\tfrom C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.22/lib/bundler.rb:10:in `<top (required)>'\r\n" +
  "\tfrom C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.22/lib/bundler/setup.rb:6:in `require_relative'\r\n" +
  "\tfrom C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.22/lib/bundler/setup.rb:6:in `<top (required)>'\r\n" +
  "\tfrom <internal:C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:148:in `require'\r\n" +
  "\tfrom <internal:C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:148:in `require'\r\n" +
  "C:/hostedtoolcache/windows/Ruby/3.1.6/x64/lib/ruby/3.1.0/rubygems/specification.rb:2163:in `method_missing': undefined method `ignored?' for #<Gem::Specification:0x000001575b219c98 @extension_dir=nil, @full_gem_path=nil, @gem_dir=nil, @ignored=nil, @bin_dir=nil, @cache_dir=nil, @cache_file=nil, @doc_dir=nil, @ri_dir=nil, @spec_dir=nil, @spec_file=nil, @gems_dir=\"C:/hostedt [...]

2024-10-18 03:09 UTC, daipom commented
I have confirmed those Windows failures have nothing to do with this change.

Currently, `multiple values are set to RUBYOPT(TestFluentdCommand::configured to run 2 workers)` fails on Ruby 3.1, 3.0 on Windows.
We need to solve this in another PR.

2024-10-18 03:09 UTC, daipom approved these changes
LGTM. Thanks!

2024-10-18 03:10 UTC, merged